<a href="https://colab.research.google.com/github/Sumit-Nayek/Data-Analytics-ans-Statistics-Assignment/blob/main/Code_mannual_assignment_7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Create two vectors and perform the following operations: dot product, element-wise multiplication, and matrix multiplication (using them as column and row vectors).

In [1]:
## 1
import numpy as np

# Create two vectors
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])

# Dot product of vectors
dot_product = np.dot(vector1, vector2)
print("Dot product of vector1 and vector2:", dot_product)

# Element-wise multiplication of vectors
element_wise_multiplication = vector1 * vector2
print("Element-wise multiplication of vector1 and vector2:", element_wise_multiplication)

# Reshape vectors for matrix multiplication
vector1_col = vector1.reshape(3, 1)  # Convert to a column vector
vector2_row = vector2.reshape(1, 3)  # Convert to a row vector

# Matrix multiplication (Outer product)
matrix_multiplication = np.dot(vector1_col, vector2_row)
print("Matrix multiplication (outer product) of vector1 and vector2:\n", matrix_multiplication)


Dot product of vector1 and vector2: 32
Element-wise multiplication of vector1 and vector2: [ 4 10 18]
Matrix multiplication (outer product) of vector1 and vector2:
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


Given a matrix, find its eigenvalues and eigenvectors. Reconstruct the matrix using its eigenvectors and eigenvalues.

In [ ]:
## 2
import numpy as np

# Define a square matrix
A = np.array([[4, -2],
              [1,  1]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

# Print the eigenvalues
print("Eigenvalues:", eigenvalues)

# Print the eigenvectors
print("Eigenvectors:\n", eigenvectors)

# Reconstruct the matrix using eigenvectors and eigenvalues
P = eigenvectors
D = np.diag(eigenvalues)
P_inv = np.linalg.inv(P)
A_reconstructed = P @ D @ P_inv

print("Reconstructed Matrix:\n", A_reconstructed)


Construct a Hadamard matrix of order 4 and perform element-wise multiplication between the Hadamard matrix and another random matrix of the same size.

In [2]:
## 3
from scipy.linalg import hadamard
import numpy as np

# Generate a Hadamard matrix of order 4
H = hadamard(4)

# Create a random 4x4 matrix
random_matrix = np.random.randint(1, 10, (4, 4))

# Element-wise multiplication of Hadamard matrix and random matrix
element_wise_multiplication = H * random_matrix
print("Hadamard Matrix:\n", H)
print("Random Matrix:\n", random_matrix)
print("Element-wise multiplication of Hadamard and random matrix:\n", element_wise_multiplication)


Hadamard Matrix:
 [[ 1  1  1  1]
 [ 1 -1  1 -1]
 [ 1  1 -1 -1]
 [ 1 -1 -1  1]]
Random Matrix:
 [[7 8 5 4]
 [3 8 8 9]
 [4 8 1 3]
 [9 4 8 1]]
Element-wise multiplication of Hadamard and random matrix:
 [[ 7  8  5  4]
 [ 3 -8  8 -9]
 [ 4  8 -1 -3]
 [ 9 -4 -8  1]]


Solve the following system of equations using matrix methods:

2
𝑥
+
3
𝑦
+
1
𝑧
=
10

4
𝑥
+
𝑦
+
2
𝑧
=
12

3
𝑥
+
2
𝑦
+
4
𝑧
=
18


In [8]:
import numpy as np

# Coefficient matrix A
A = np.array([[2, 3, 1],
              [4, 1, 2],
              [3, 2, 4]])

# Constant matrix B
B = np.array([10, 12, 18])

# Solve the system A * [x, y, z] = B
solution = np.linalg.solve(A, B)

print("Solution for [x, y, z]:", solution)


Solution for [x, y, z]: [1.2 1.6 2.8]


Solve the system of linear equations using matrix methods:

2
𝑥
+
3
𝑦
=
5

4
𝑥
+
𝑦
=
6

In [7]:
## 5
import numpy as np

# Coefficient matrix A
A = np.array([[2, 3],
              [4, 1]])

# Constant matrix B
B = np.array([5, 6])

# Solve the system of equations A * [x, y] = B
solution = np.linalg.solve(A, B)

print("Solution for [x, y]:", solution)


Solution for [x, y]: [1.3 0.8]
